### ISSUE TITLE
readme problem

### ISSUE THREAD

**Issue by Polandia94** [nicolasgarcia214/damn-vulnerable-defi-foundry#1]
git clone git@github.com:nicolasgarcia214/damn-vulnerable-defi-foundry.git 
doesn't allow to clone in my enviroment (bash, ubuntu). 

git clone https://github.com/nicolasgarcia214/damn-vulnerable-defi-foundry.git 
work ok to me

**Comment by nicolasgarcia214** [comment]
I'm used to working with ssh so but it makes sense to have a more general command on the docs. Thanks for playing it and let me know how you liked it. 👍
