### ISSUE TITLE
SideEntrance Test setUp assert fails

### ISSUE THREAD

**Issue by chad-mcdonald** [nicolasgarcia214/damn-vulnerable-defi-foundry#4]
https://github.com/nicolasgarcia214/damn-vulnerable-defi-foundry/blob/6a33a970ba2c8e8eb24c939e3c28870195dd72bb/src/test/Levels/side-entrance/SideEntrance.t.sol#L21-L35

The setUp function ends with an assert check that the attacker's address holds 0 Ether.  This assert fails because when a new user account is created from Utilities (attacker in this case) 100 eth is automatically dealt to that account.

**Comment by chad-mcdonald** [comment]
Created a PR for it here: #5

**Comment by nicolasgarcia214** [comment]
In the internal branch with the solutions I don't have the assertion line and that must be why I didn't notice that it had an error 😅. Thanks for pointing that out.

**Comment by nicolasgarcia214** [comment]
Solved [here](https://github.com/nicolasgarcia214/damn-vulnerable-defi-foundry/commit/501bedf07e77f162844860838c36f81c356814bd)
